### ISSUE TITLE
[spawn_model-4] process has died 

### ISSUE THREAD

**Issue by DavidNguyen95** [pal-robotics/tiago_simulation#17]
Now I am using a docker (that has pytorch and cuda inside : `pytorch/pytorch:1.8.1-cuda10.2-cudnn7-devel ` ) because we need to use GPU , then i install tiago package inside that docker. In general docker build  and rocker run docker container complete.

Inside docker container
When I run roslaunch a simulation `roslaunch tiago_gazebo tiago_gazebo.launch public_sim:=true robot:=steel
`  
Gazebo ran but without tiago model inside, on the terminal there is a error like fail when load URDF model. More detail about error here:

> [spawn_model-4] process has died [pid 673, exit code 1, cmd /tiago_public_ws/src/gazebo_ros_pkgs/gazebo_ros/scripts/spawn_model -urdf -param robot_description -x 0.0 -y 0.0 -z 0.0 -R 0.0 -P 0.0 -Y 0.0 -model tiago __name:=spawn_model __log:=/root/.ros/log/c92a57de-ea5d-11eb-b926-0242ac110002/spawn_model-4.log].
log file: /root/.ros/log/c92a57de-ea5d-11eb-b926-0242ac110002/spawn_model-4*.log
 
1. Can you have any suggestion for me? to fix the issue.

2. Or suggest me other way to make dockerfile that can use GPU ( cuda, Pytorch ).  I tried to use tiago docker (docker base on `osrf/ros:melodic-desktop-full-bionic` ) it work good with tiago package but it doesn't have cuda and pytorch inside. Can anyone suggest me install cuda inside tiago docker? 
Many thanks
Dat

**Comment by saikishor** [comment]
Hello,

Closing the issue as it is out-of-date.

Best Regards,
PAL Robotics Team.
