### ISSUE TITLE
Launching omni_base_description

### ISSUE THREAD

**Issue by eliastreis** [pal-robotics/tiago_simulation#18]
Hi,
when I try to run tiago with `omni_base` insted of `pmb2` I run at this line into a problem:`([here](https://github.com/pal-robotics/tiago_robot/blob/e2a3a4010d8865e9655c483f9143f59c140fbd39/tiago_description/robots/tiago.urdf.xacro#L73))
```xml
  <xacro:include filename="$(find ${base_type}_description)/urdf/base/base_sensors.urdf.xacro" />
```
since he does not find `omni_base_description`. Is this package also available on github (I was only able to find `pmb2_description`)?

**Comment by saikishor** [comment]
Hello @eliastreis,

Thank you for showing interest in our TIAGo family and it's variants. We are currently working to make the `omni_base` variant of our TIAGo family public. We will be publishing the packages and the tutorials for the `omni_base` variant in a couple of weeks. We will keep you posted.

Thank you,

Best Regards,
PAL Robotics Team
