### ISSUE TITLE
RViz doesn't display TIAGo's depth image in ROS2 Humble simulation

### ISSUE THREAD

**Issue by jmguerreroh** [pal-robotics/tiago_simulation#21]
The image published on the topic `/head_front_camera/depth_registered/image_raw` cannot be displayed in RViz

![image](https://user-images.githubusercontent.com/55832002/222139488-565005a4-1c8b-4541-be84-b63013644252.png)

**Comment by saikishor** [comment]
Hello @jmguerreroh,

Please kindly provide us with more info so we could reproduce the issue. on TIAGo melodic and noetic, you can get the depth image from the topic : `/xtion/depth_registered/image_raw`.

Thank you,

Best Regards,
PAL Robotics Team.

**Comment by jmguerreroh** [comment]
Hello @saikishor ,

I am using Ubuntu 22.04 and ROS Humble distro. Topic `/xtion/depth_registered/image_raw` does not exists due its occurs in the simulated TIAGo, so the topic is `/head_front_camera/depth_registered/image_raw` and depth image in RViz is dark.

After different times or head movements, the image is displayed, but not always.

Thank you.

**Comment by saikishor** [comment]
Hello @jmguerreroh,

First of all, sorry for the delay in responding to your issue. Regarding your issue, we could reproduce the same issue on our end, where it works very few times, but not most of the time. However, after looking into it, we have seen others have faced a similar issue, and it seems to do something with the QoS settings of the RViz. You can find the reference issue here: https://answers.ros.org/question/371730/ros2-gazebo-camera-not-publishing-data/

If you visualize the same with the rqt_image_view node, you won't have the issue. I'm attaching an image for your reference. 

![image](https://user-images.githubusercontent.com/10082428/231501969-941f1fc9-e3e5-48b2-b410-77e8161c4c11.png)

I'll be closing the issue, as the issue doesn't seem to be on our end. 

Thank you,

Best Regards,
PAL Robotics Team.
