### ISSUE TITLE
Joint State Publisher ROS2 Humble

### ISSUE THREAD

**Issue by kavikode** [pal-robotics/tiago_simulation#30]
Having a very difficult time with running the joint state publisher to control the simulation in Zazebo for ROS 2 because I'm very new learner.

Can you please provide the steps to control the joints for your simulation?

Thank you

**Comment by Noel215** [comment]
Hi @kavikode,

You should be able to move the joints individually by using the `rqt-joint-trajectory-controller` or using `rviz2`, as explained in the README of the repository.

**Comment by kavikode** [comment]
thank you
