### ISSUE TITLE
MoveIt_PY: Motion Planning Python API

### ISSUE THREAD

**Issue by kavikode** [pal-robotics/tiago_simulation#31]
Following the example In the link: https://moveit.picknik.ai/main/doc/examples/motion_planning_python_api/motion_planning_python_api_tutorial.html

We'd like to perform motion planning for the Tiago robot simulation by specifying a goal state via a ROS message representing the pose goal. 

Will you please provide an example of how to set and execute plan of a pose goal for the end effector of the Tiago robot in a the  moveit_py node and a yaml configuration file that defines the associated parameters for the defined moveit_py node?

Is there existing example? Thank you so much!

**Comment by Noel215** [comment]
Hi @kavikode,

I'm afraid we currently do not have an example for planning and executing a trajectory using MoveIt2. We do intend to include such an example in our tutorials in the future; however, I am unable to provide a specific timeline for its availability at this time.
