### ISSUE TITLE
Latest Commit does not launch the robot

### ISSUE THREAD

**Issue by kavikode** [pal-robotics/tiago_simulation#32]
executing command [sudo -H apt-get install -y ros-humble-pal-maps]
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package ros-humble-pal-maps
ERROR: the following rosdeps failed to install
  apt: command [sudo -H apt-get install -y ros-humble-pal-maps] failed

how can we resolve this?

**Comment by Noel215** [comment]
Hi @kavikode,

The repository is released to humble. See https://github.com/ros/rosdistro/blob/master/humble/distribution.yaml#L5328

If you run `sudo apt update` you should be able to install it.

```
~# apt-cache search pal-maps
ros-humble-pal-maps - Public Maps used for the Navigation of PAL Robotics robots.
```

**Comment by kavikode** [comment]
thanks
